// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYL-skSp_kfklpf2jy3NlCqJwrUzuIwZM',
    appId: '1:653844014276:web:13a72d4d04886236185591',
    messagingSenderId: '653844014276',
    projectId: 'database-a1f2a',
    authDomain: 'database-a1f2a.firebaseapp.com',
    databaseURL: 'https://database-a1f2a-default-rtdb.firebaseio.com',
    storageBucket: 'database-a1f2a.firebasestorage.app',
    measurementId: 'G-6ZG51LRLY4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpZAy-vUBEnmoATH_-i-hrARd0RTEj3Ao',
    appId: '1:653844014276:android:a6392a35b9697770185591',
    messagingSenderId: '653844014276',
    projectId: 'database-a1f2a',
    databaseURL: 'https://database-a1f2a-default-rtdb.firebaseio.com',
    storageBucket: 'database-a1f2a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZzFzGeee4k36sI7GvL9oDOAIHjiOXiU4',
    appId: '1:653844014276:ios:0f22037f17b15516185591',
    messagingSenderId: '653844014276',
    projectId: 'database-a1f2a',
    databaseURL: 'https://database-a1f2a-default-rtdb.firebaseio.com',
    storageBucket: 'database-a1f2a.firebasestorage.app',
    iosClientId: '653844014276-8cvu0gqru2n6spadp7cvg9on9k0ds2iu.apps.googleusercontent.com',
    iosBundleId: 'com.example.safetyPortal',
  );
}

const String geminiApiKey = "AIzaSyDxEQLJWTuzI-5ZLPVGgaYY6ci4_MkApOg"; 

const String appsScriptUrl = ""; 